name: archcode-sandbox CI

on:
  push:
    # déclenche sur branches archcode-self/*
    branches:
      - 'archcode-self/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: archcode-sandbox-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: ${{ github.workspace }}   # permet `import core`, `import agents.*` depuis repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (pip + pyyaml)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # installer au minimum PyYAML + outils utiles
          pip install pyyaml ruff pytest || true

      - name: Show python & pip info
        run: |
          python --version
          pip --version
          python -c "import yaml; print('PyYAML OK', yaml.__version__)"
          pip list --format=columns

      - name: Check GH_PAT secret exists
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "${GH_PAT}" ]; then
            echo "::warning ::Secret GH_PAT is missing or not available in this run."
            echo "If you rely on tag/remote pushes, create the GH_PAT secret in repository Settings → Secrets and variables → Actions"
          else
            echo "GH_PAT looks available (masked)."
          fi

      - name: Aggregate modules → plan_draft_aggregated.yaml (PGA)
        run: |
          # --only-ok retiré car l'agent ne le supporte pas dans cette version
          python -m agents.agent_module_compilator collect \
            --reset-if-missing --update-ec

      - name: Validate plan → plan_validated.yaml (PV)
        run: |
          python -m agents.agent_plan_validator validate --update-ec

      - name: Build execution_plan.yaml
        run: |
          python -m scripts.execution_plan_transformer build

      - name: Lint (ruff) — optionnel (non bloquant)
        continue-on-error: true
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check .
          else
            echo "ruff not installed — skipping lint"
          fi

      - name: Tests (pytest) — optionnel (non bloquant)
        continue-on-error: true
        run: |
          if [ -f pytest.ini ] || [ -d tests ] || [ -f requirements.txt ]; then
            pytest -q || true
          else
            echo "No tests found — skipping pytest"
          fi

      - name: List .archcode artifacts (for debugging)
        if: always()
        run: |
          echo "ls -la .archcode || true"
          ls -la .archcode || true
          echo "show yaml heads"
          for f in .archcode/*.yaml; do
            [ -f "$f" ] || continue
            echo "---- $f ----"
            head -n 80 "$f" || true
          done

      - name: Upload .archcode artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: archcode-artifacts
          path: .archcode/*.yaml
